# https://taskfile.dev

version: '3'

vars:
  MODNAME: shuttle-conductor

tasks:
  symlink:
    platforms: [windows]
    cmds:
      # This command creates a symbolic link to the mod in the Factorio mods folder by making CMD launch Powershell to make it launch CMD as an administrator so it can use mklink. Fun.
      - powershell -Command "Start-Process cmd -Verb RunAs -Argument '/c mklink /D %appdata%\Factorio\Mods\{{.MODNAME}} {{.USER_WORKING_DIR}}\..\{{.MODNAME}}'"
  unlink:
    platforms: [windows]
    dir: '{{.APPDATA}}\Factorio\Mods'
    cmds:
      # This command removes the symbolic link. WOOOOO
      # (don't remove the CMD part, it will remove the files if you do!)
      - cmd /c rmdir {{.MODNAME}}
  debug-folder:
    platforms: [windows]
    dir: '{{.APPDATA}}\Factorio'
    cmds:
      - cmd /c ren Mods disabledMods
      - cmd /c ren debugMods Mods
  undebug-folder:
    platforms: [windows]
    dir: '{{.APPDATA}}\Factorio'
    cmds:
      - cmd /c ren Mods debugMods
      - cmd /c ren disabledMods Mods